# ============================================================================
# DUKANX ENTERPRISE ANALYSIS OPTIONS
# ============================================================================
# Balanced linting: focused on safety rules that prevent crashes.
# Style rules disabled to reduce noise during development.
#
# Author: DukanX Engineering
# Version: 2.2.0 (Production Ready)
# ============================================================================

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # =========================================================================
    # CRITICAL SAFETY RULES (ENABLED)
    # =========================================================================
    
    # Avoid empty catch blocks
    empty_catches: true
    
    # Close resources properly
    close_sinks: true
    cancel_subscriptions: true
    
    # Always await futures (CRITICAL - causes race conditions)
    unawaited_futures: true
    
    # Performance
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    
    # Widget best practices
    use_key_in_widget_constructors: true
    
    # =========================================================================
    # STYLE RULES (DISABLED - too noisy)
    # =========================================================================
    
    # These are good practices but generate too many warnings
    prefer_const_constructors: false
    prefer_const_declarations: false
    prefer_const_constructors_in_immutables: false
    prefer_const_literals_to_create_immutables: false
    prefer_final_locals: false
    prefer_final_fields: false
    prefer_final_in_for_each: false
    
    # Other noisy rules
    avoid_print: false
    avoid_dynamic_calls: false
    only_throw_errors: false
    deprecated_consistency: false
    unnecessary_this: false
    unnecessary_new: false

# =========================================================================
# ANALYZER CONFIGURATION
# =========================================================================
analyzer:
  errors:
    # Ignore these during migration
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    
    # Keep safety rules as warnings
    unawaited_futures: ignore  # Most are intentional fire-and-forget patterns
    empty_catches: warning
    cancel_subscriptions: warning
    close_sinks: warning
    
  exclude:
    # Generated files
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "build/**"
    - ".dart_tool/**"
