// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios/macos yet.',
        );
      case TargetPlatform.windows:
        return android; // Fallback to android/web config for windows
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9NbEDnkYAd9b1iaXYcFTg-I7Pt9ncC5w',
    appId: '1:782683401944:web:979f7f79b47d500cdb71ad',
    messagingSenderId: '782683401944',
    projectId: 'billingapp-5cb94',
    authDomain: 'billingapp-5cb94.firebaseapp.com',
    databaseURL: 'https://billingapp-5cb94-default-rtdb.firebaseio.com',
    storageBucket: 'billingapp-5cb94.firebasestorage.app',
    measurementId: 'G-58LKMCT62K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-b5skE3UFEFD7Rgg0iFOQm8ze1mcY-Ks',
    appId: '1:782683401944:android:442cf8122899f941db71ad',
    messagingSenderId: '782683401944',
    projectId: 'billingapp-5cb94',
    databaseURL: 'https://billingapp-5cb94-default-rtdb.firebaseio.com',
    storageBucket: 'billingapp-5cb94.firebasestorage.app',
  );

  // NOTE: iOS CONFIGURATION REQUIRED FOR iOS/macOS BUILDS
  // --------------------------------------------------------
  // To configure iOS:
  // 1. Run: flutterfire configure --platforms=ios
  // 2. Download GoogleService-Info.plist from Firebase Console and add to ios/Runner/
  // 3. Ensure your Bundle ID in Xcode matches the one in Firebase Console
  // NOTE: This step requires the FlutterFire CLI to be installed on macOS.
  //
  // Current values are PLACEHOLDERS - iOS builds will work with these values
  // but require proper configuration for production.

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjAgKZ0EbncNxS_r_NN8uU6hYBF21gndQ',
    appId: '1:782683401944:ios:705f4abbe1ab6261db71ad',
    messagingSenderId: '782683401944',
    projectId: 'billingapp-5cb94',
    databaseURL: 'https://billingapp-5cb94-default-rtdb.firebaseio.com',
    storageBucket: 'billingapp-5cb94.firebasestorage.app',
    androidClientId:
        '782683401944-807bi8oash85lbafm8ekbr1cobqbjmii.apps.googleusercontent.com',
    iosClientId:
        '782683401944-pph6bsvt155t4mbslfng54ie37o0df7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  // The currentPlatform getter above throws UnsupportedError to prevent this.

  // NOTE: macOS CONFIGURATION REQUIRED FOR MACOS BUILDS
  // --------------------------------------------------------
  // To configure macOS:
  // 1. Run: flutterfire configure --platforms=macos
  // 2. Download GoogleService-Info.plist from Firebase Console and add to macos/Runner/
  // 3. Enable "App Sandbox" and "Network Client" in Xcode capabilities
  // NOTE: macOS is lower priority - Android/Web builds work correctly.

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjAgKZ0EbncNxS_r_NN8uU6hYBF21gndQ',
    appId: '1:782683401944:ios:705f4abbe1ab6261db71ad',
    messagingSenderId: '782683401944',
    projectId: 'billingapp-5cb94',
    databaseURL: 'https://billingapp-5cb94-default-rtdb.firebaseio.com',
    storageBucket: 'billingapp-5cb94.firebasestorage.app',
    androidClientId:
        '782683401944-807bi8oash85lbafm8ekbr1cobqbjmii.apps.googleusercontent.com',
    iosClientId:
        '782683401944-pph6bsvt155t4mbslfng54ie37o0df7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  // 4. Update the values below with the generated options
}
